name: flutter_application_7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
 
   
    